Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box_check_update = false
  config.vm.boot_timeout = 1440

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 1
    #vb.gui = true
  end

  config.vm.define "lamp" do |lamp|
    lamp.vm.network "private_network", ip: "10.10.0.11"
    lamp.vm.hostname = "lamp"
    lamp.vm.provision "shell", inline: <<-SHELL
      sudo apt-get clean
      sudo apt update -y
      sudo apt install apache2 mysql-server php7.4 -y
    SHELL
  end

  config.vm.define "docker" do |docker|
    docker.vm.network "private_network", ip: "10.10.0.12"
    docker.vm.hostname = "docker"
    docker.vm.provision "shell", inline: <<-SHELL
      apt-get clean
      apt update -y
    SHELL
  end

  config.vm.provision "shell", inline: <<-SHELL
      apt-get clean
      apt update -y
    SHELL
  end