
Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  #config.vm.box_version = "1.0.282"
  #config.vm.box_url = "https://vagrantcloud.com/hashicorp/bionic64"
  config.vm.hostname = "myapache2"
  config.vm.provision :shell, path: "script.sh"
  config.vm.synced_folder ".", "/var/www/html"
  config.vm.network "private_network", ip: "192.168.54.1"
  config.vm.network :forwarded_port, guest: 80, host: 8000

end
