# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  # boxes at https://vagrantcloud.com/search.
  # config.ssh.insert_key = false
  config.vm.box_check_update = false
  config.vm.boot_timeout = 1440
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
    vb.cpus = 1
  end

  # Master
  config.vm.define "master" do |master|
    master.vm.box = "geerlingguy/centos7"
    master.vm.hostname = "master"
    master.vm.network :private_network, ip: "10.10.60.3"
    master.vm.provision "shell", inline: <<-SHELL
      yum install epel-release
      yum -y install ansible
    SHELL
  end

  # Application server 1.
  config.vm.define "app1" do |app1|
    app1.vm.hostname = "app1"
    app1.vm.box = "geerlingguy/centos7"
    app1.vm.network :private_network, ip: "10.10.60.4"
  end

  # Application server 2.
  config.vm.define "app2" do |app2|
    app2.vm.hostname = "app2"
    app2.vm.box = "geerlingguy/centos7"
    app2.vm.network :private_network, ip: "10.10.60.5"
  end

  # Database server.
  config.vm.define "db" do |db|
    db.vm.hostname = "db"
    db.vm.box = "geerlingguy/centos7"
    db.vm.network :private_network, ip: "10.10.60.6"
  end

end
